server:
  port: 13000

spring:
  application:
    name: notificaiton-service

  config:
    # 유레카를 거치지 않고 직접 쿠버네티스 서비스 주소로 찌름
    import: 'optional:configserver:http://config-server.next-me.svc.cluster.local:3100'
  cloud:
    config:
      discovery:
        enabled: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: notification-service
      auto-offset-reset: earliest

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server.next-me.svc.cluster.local:3151/eureka/

slack:
  token: ${SLACK_OAUTH_TOKEN}

promotion:
  service:
    url: ${PROMOTION_SERVICE_URL}

logging:
  level:
    org.springframework.security: INFO
