server:
  port: 13000

spring:
  application:
    name: notificaiton-service

  config:
    import: "configserver:http://13.210.162.214:3100"

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: notification-service
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: org.nextme.notificationservice.infrastructure.kafka.event.MonitoringNotificationEvent

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}

slack:
  token: ${SLACK_OAUTH_TOKEN}

logging:
  level:
    org.springframework.security: INFO